apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
data:
  vmagent.yaml: |
    global:
      scrape_interval: {{ .Values.staging.config.scrape_interval | default "30s" }}

    scrape_configs:
    - job_name: {{ .Values.staging.config.job_name | quote }}
      static_configs:
      - targets:
{{ toYaml (default list .Values.staging.config.targets) | indent 8 }}
        labels:
{{ toYaml (default dict .Values.staging.config.labels) | indent 10 }}