apiVersion: v1
kind: ConfigMap
metadata:
  name: vmagent-config
data:
  config.yaml: |
    global:
{{ toYaml .Values.config.global | indent 6 }}

    scrape_configs:
{{ toYaml .Values.extraScrapeConfigs | indent 6 }}