apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: {{ .Values.namespace }}
  labels:
    app: vmagent
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
      annotations:
        configmap-hash: "CHANGE_ME_HASH"
    spec:
      containers:
      - name: vmagent
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
          - "-promscrape.config=/etc/vmagent/vmagent.yaml"
          - "-remoteWrite.url={{ .Values.remoteWriteUrl }}"
        volumeMounts:
        - name: config
          mountPath: /etc/vmagent
        resources:
          requests:
            memory: "{{ .Values.resources.requests.memory }}"
            cpu: "{{ .Values.resources.requests.cpu }}"
          limits:
            memory: "{{ .Values.resources.limits.memory }}"
            cpu: "{{ .Values.resources.limits.cpu }}"
      volumes:
      - name: config
        configMap:
          name: vmagent-config