apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmagent
  namespace: {{ .Values.frontend.namespace }}
  labels:
    app: vmagent
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: vmagent
  template:
    metadata:
      labels:
        app: vmagent
      annotations:
        # 可以用 ConfigMap hash 或 CI/CD 替换
        configmap-hash: "CHANGE_ME_HASH"
    spec:
      containers:
      - name: vmagent
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        args:
          - "-promscrape.config=/etc/vmagent/vmagent.yaml"
          - "-remoteWrite.url={{ .Values.frontend.remoteWriteUrl }}"
        volumeMounts:
        - name: config
          mountPath: /etc/vmagent
      volumes:
      - name: config
        configMap:
          name: vmagent-config