remoteWrite:
  - url: http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/0/prometheus/

mode: deployment
replicaCount: 2

deployment:
  spec:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%

image:
  repository: victoriametrics/vmagent
  tag: v1.106.0
  pullPolicy: IfNotPresent

# serviceAccount:
#   create: true

# rbac:
#   create: true

namespace: monitoring
