remoteWrite:
  - url: http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/0/prometheus/

replicaCount: 1
deployment:
  enabled: true
rbac:
  enabled: false
serviceAccount:
  enabled: false   
env:
  - name: ENV_VAR
    value: "just make sure that env var works"
