remoteWrite:
  - url: http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/0/prometheus/

replicaCount: 1
deployment:
  enabled: true

serviceAccount:
  enabled: false   
env:
  - name: ENV_VAR
    value: "just make sure that env var works"



config:
  scrape_interval: 30s
  job_name: "Tomcat-jvm"
  targets:
    - "tomcat-1:9404"
    - "tomcat-2:9404"
    - "10.31.192.120:9404"
  labels:
    env: 'staging'
    application: 'tomcat'    