victoria-metrics-agent:
  deployment:
    enabled: true

  replicaCount: 3

  service:
    enabled: false
  rbac:
    create: false
    
  serviceAccount:
    create: false
    name: ""

  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 2
  remoteWrite:
    - url: http://cluster-victoria-metrics-cluster-vminsert.default.svc.cluster.local:8480/insert/0/prometheus/
