annotations:
  artifacthub.io/category: monitoring-logging
apiVersion: v2
appVersion: v1.137.0
keywords:
- vmagent
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-agent
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.33.0
